# Generated by Django 3.2.8 on 2022-01-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211230_1043'),
        ('blog', '0004_alter_artikel_body'),
    ]

    operations = [
    ]
